### ISSUE TITLE
Hibernate-redis second-level cache is hash type in redis, how to config expiration time of each hashkey

### ISSUE THREAD

**Issue by hegphegp** [debop/hibernate-redis#142]

**Comment by hegphegp** [comment]
* My project is generated by Springboot, the config params are followed these
```
spring.jpa:
  hibernate.ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  properties.hibernate.temp.use_jdbc_metadata_defaults: false
  properties.redis:
    expiryInSeconds:
      default: 120
      hibernate:
        common: 0
        account: 1200
  properties.hibernate:
    cache:
      use_second_level_cache: true
      use_query_cache: true
      region.factory_class: xxx.xxx.cache.hibernate.CacheRegionFactory
      region_prefix: hibernate
      use_structured_entries: true
```
