### ISSUE TITLE
Can you support read config  from spring boot application.properties?

### ISSUE THREAD

**Issue by Dreampie** [debop/hibernate-redis#64]
like this(application.yml):
```
spring:
  datasource:
  # ...
  jpa:
    showSql: true
    hibernate:
      ddlAuto: validate
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          transaction:
            factory_class: org.hibernate.engine.transaction.internal.jdbc.JdbcTransactionFactory
          region:
            factory_class: org.hibernate.cache.redis.SingletonRedisRegionFactory
          redis:
            expiry_in_seconds: 0 #秒
```
